{{- range $hostName := .Values.domainNames }}
{{- $normalizedHostName := $hostName | replace "." "-" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ $normalizedHostName }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: {{ $hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Values.serviceName }}
            port:
              number: {{ $.Values.servicePort }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $hostName }}
    secretName: keyvault-ingress-{{ $normalizedHostName }}
---
{{- end }}