apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpecho
  template:
    metadata:
      labels:
        app: httpecho
    spec:
      containers:
      - name: httpecho
        image: mendhak/http-https-echo:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: httpecho
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP